### ISSUE TITLE
files with multiple sampling rate in the same page produce incorrect lengths

### ISSUE THREAD

**Issue by giuliomoro** [BrechtDeMan/WebAudioEvaluationTool#100]
these are the durations from the save.xml file

````
<file sampleRate="44100" channels="2" sampleCount="6816001" duration="154.55784580498866"></file>
<file sampleRate="44100" channels="2" sampleCount="6816001" duration="154.55784580498866"></file>
<file sampleRate="44100" channels="2" sampleCount="6816001" duration="154.55784580498866"></file>
<file sampleRate="44100" channels="2" sampleCount="6816001" duration="154.55784580498866"></file>
<file sampleRate="44100" channels="2" sampleCount="6816001" duration="154.55784580498866"></file>
<file sampleRate="96000" channels="1" sampleCount="6816001" duration="71.00001041666667"></file>
````
while the sample count of the actual files is 
1940401frames (3880802 samples) (stereo, 44.1kHz) for the first 4 
 and 
4224001frames (4224001 samples) (mono, 96kHz) for the last one 

and the duration is 44 seconds for all of them

have fun :)

**Comment by BrechtDeMan** [comment]
I didn't realise we supported multiple sample rates already. Cool! 

@giuliomoro, is it just the numbers in this file that are wrong, or are they actually chopped off when you listen to them? I suppose the `duration` of all needs to be 44 seconds, i.e. those numbers are wrong too? 

I can't be of much help, though now I'm wondering what happens if you force a certain system sample rate, e.g. `<setup interface="AB" projectReturn="save.php" randomiseOrder="true" sampleRate="44100">`. Do we just check the system's sample rate is the same as that one, and let the Web Audio API automatically resample whatever is not at that rate? @nickjillings

**Comment by giuliomoro** [comment]
Well it looks like they are not supported. Not properly at least. Not by me, but Dave and Dave used me as a Guinea pig on a test where they had multiple sampling rate (by mistake).
I actually have a video of what happened 
https://youtu.be/G_mFfTgnLeg
silence tails were added to all the files ( that is why the reported duration was longer than the actual duration of the files).

I am sure it is an edge case when files with differing sampling rates are present in a given page, but it should be supported anyhow. 

This would eventually lead to the ultimate test "evaluate the sampling rate converter in your browser"

**Comment by nickjillings** [comment]
These are all read from the decoded buffer so not sure what is happening. Shouldn't be any calculations. Can you inform me which browser this was on. Should be in the results file

Sent from my iPhone

On 24 May 2016, at 21:58, Brecht De Man <notifications@github.com<mailto:notifications@github.com>> wrote:


I didn't realise we supported multiple sample rates already. Cool!

@giuliomoro<https://github.com/giuliomoro>, is it just the numbers in this file that are wrong, or are they actually chopped off when you listen to them? I suppose the duration of all needs to be 44 seconds, i.e. those numbers are wrong too?

I can't be of much help, though now I'm wondering what happens if you force a certain system sample rate, e.g. <setup interface="AB" projectReturn="save.php" randomiseOrder="true" sampleRate="44100">. Do we just check the system's sample rate is the same as that one, and let the Web Audio API automatically resample whatever is not at that rate? @nickjillings<https://github.com/nickjillings>

-

**Comment by giuliomoro** [comment]
Chrome on Version 50.0.2661.102 (64-bit) Mac OS 10.11.3

Note from the video that when selecting the 96kHz track, the scroll bar size changes. Also, all of the tracks have silence appended at the end, with the 44.1kHz tracks having the same amount of silence between them (but more than the 96kHz mono one)

**Comment by nickjillings** [comment]
I don't think the silence calculator takes into account the sample rate of the underlying buffer! That may be causing some of the issues. I think also the sample_count of the AudioBuffer objects is the total sample_count (hence the stereos are double what they should be).
