### ISSUE TITLE
background loading of audio files may slow down the client

### ISSUE THREAD

**Issue by giuliomoro** [BrechtDeMan/WebAudioEvaluationTool#102]
I was doing this test by Dave and Dave and I was at QM and the files were on webprojects.eecs.qmul.ac.uk server.

Throughout the 3/4 pages of the pre_survey, my client (Chrome Mac OS) was slow and glitchy. I believe it may have been because it was loading in the background 5*5*96kHz*45seconds tracks.

Is there any way to make sure the GUI does not slow down because of the background buffering?

**Comment by nickjillings** [comment]
I'm not sure what is causing the slow down. There is an event which is fired for each buffer on progress update events, however unless the buffer is already assigned to an audioObject the function quits nearly immediately. That may be causing some issues (since even executing an almost empty function still takes some time) but it shouldn't be too bad.

The real time takers with that function is when an audioObject is waiting for a buffer, then it modifies the on-screen elements to show an update / download progress percentage. Again this is small.

A more plausable location may be when the buffer has finished loading. At that point the loudness is triggered which may be taking up a fair chunk of CPU time.

The only way to know for sure is to run profiling on this.

**Comment by BrechtDeMan** [comment]
Or to not run loudness.js? Isn't that only executed if there is a `loudness="-23"` type of attribute?

**Comment by nickjillings** [comment]
@BrechtDeMan it's a little tricky. What is page 0 has loudness set but page 1 doesn't. Currently all the audio elements are extracted from the pages and queued up, that way if fragments appear multiple times (same page / many page) it is only loaded up once. To facilitate this the loudness is always assumed to be needed.

A better way may be to leverage the [WebWorkers ](https://www.w3.org/TR/workers/)([http://caniuse.com/#search=Workers](http://caniuse.com/#search=Workers) to offload the rendering of loudness. It shouldn't be any harder since the whole process is already an asynchronous chain.

From profiling it seems that a large amount of time is going into a function called 'integerConvert' which converts the WAVE file Integer bitstream into a Float32Array. Ideally removing this will save a lot more time by defaulting the browser to use the internal decoder unless it cannot be supported. Currently we always attempt to use WAVE and fallback to the browser if it is something else (MP3 etc).

**Comment by nickjillings** [comment]
Another method may be a special 'slow-load' option or a 'max-queue' option whereby files are scheduled into several pipelines based on the page order. That way it is less likely that there will be multiple large files all trying to decode at once.

**Comment by nickjillings** [comment]
I've swapped around the decoder order to default to using the in-built decoder. Can someone update Dave's test to the lastest master ( a44093ffb67)
