### ISSUE TITLE
Test never fully loading on iOS

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#121]
On iPhone 5, iOS 8.2

[This page](http://webprojects.eecs.qmul.ac.uk/bdm30/mixevaluation1.2/test.html?url=salford.xml) never fully loads, and displays a 'page had to be reloaded' error message. It would keep reloading like this the whole time.

**Comment by nickjillings** [comment]
It does seem that this has resolved over the years, just testing all interfaces.

APE has some issues but they're covered in #122

**Comment by nickjillings** [comment]
State of interfaces on iOS (iPad):

 - MUSHRA: OK
 - APE: Axis labels incorrect, cannot reliably drag or start playback
 - AB: OK
 - ABX: X doesn't show, actually seems to be from #243 
 - Discrete: OK
 - horizontal: Some text issues with the scales
 - ordinal: Can't move but I think because the viewport moves on touch and isn't locked for ordinal

So this bug is resolved, the others I'll create new tracks for them individually as needed
