### ISSUE TITLE
AB Test - Force fragmentMoved broken

### ISSUE THREAD

**Issue by djmoffat** [BrechtDeMan/WebAudioEvaluationTool#131]
When I `<interfaceoption type="check" name="fragmentMoved”/>` - this is meant to force the person to pick before moving to the next page? - this doesn’t work for AB tests.
I am able to listen to both samples then move to the next page without selecting one.

Documentation says 
> fragmentMoved: Checks that all fragments have been moved. This is interface de- pendent, for instance on AB this will always clear as there is no movement.

but how do I force the AB test to ensure a choice is made?

**Comment by nickjillings** [comment]
The problem is that when you click on a source we track the movement for all nodes, so if I have options A, B and C. If I click B, then I click C, I've actually never moved A but it will still track I have (because we effectively say the one that is selected is at value 100, all others at value 0).

Therefore whilst it is 'moved' it is not explicitly ever selected by the user and therefore it is rather useless in that regard.

The best way is to enforce a scale range by using `<interfaceoption type="check" name="scalerange" min="25" max="75"/>`. This will check for a node above 75, which there will only be if one is selected.

**Comment by nickjillings** [comment]
Note, if you only have one item on a page, perhaps for demonstrating reasons, this will completely stall the test since it also requires a node below 25 (or at 0 for AB) and one node cannot be at both 100 and 0.

**Comment by djmoffat** [comment]
applying `<interfaceoption type="check" name="scalerange" min="25" max="75"/>` is a great way of doing it - you are right - but is there an option to edit the error message that is displayed?

**Comment by nickjillings** [comment]
Not yet but I have thought about this as it would not be too difficult to add. Feature request it!

**Comment by BrechtDeMan** [comment]
Cool beans. I'm wondering if we should make a specific wiki page for every interface type, especially if there are 'tips' like the above (use a scalerange check to make sure something was answered). I could easily do this for APE, perhaps those who have experience with AB(X) ( @djmoffat , @giuliomoro ) could document that one, ...

I don't quite understand the behaviour of moving a sample to 100 just by auditioning it. Should this not be controlled by 'fragmentPlayed' etc., while the fragmentMoved stuff is about actually selecting it?

**Comment by nickjillings** [comment]
It doesn't. There are separate play and select buttons, the movement only occurs when you use the select buttons. It is one of those 'at the time' it made a lot of sense, but now I think actually the fragmentMoved probably should be enabled and instead have the caveat of 'if any were selected it will count all of them as moved' as I think that makes more sense than 'use the scale range to enforce usage on a non-scaled event'.

**Comment by BrechtDeMan** [comment]
> the fragmentMoved probably should be enabled and instead have the caveat of 'if any were selected it will count all of them as moved' as I think that makes more sense than 'use the scale range to enforce usage on a non-scaled event'.

So you're saying adding `<interfaceoption type="check" name="fragmentMoved”/>` should only check whether a sample was selected 'at some point'? Or should it check if it was still selected at the very end? 
Surely you don't need the subject to effectively select all of them once, right? (Audition: yes/maybe; select: not necessarily)
I'm not sure I understand what the problem is/was, and what you suggest the desired functionality is.

**Comment by nickjillings** [comment]
It would just require that one of them was selected at some point as all of them will get a moved event.

**Comment by BrechtDeMan** [comment]
Sounds good, though then it would only be possible to enforce 'one option needs to be selected' i.e. 'you need to pick A or B' by doing the scalerange thing? Isn't that the current state of things?
