### ISSUE TITLE
Slider survey element

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#137]
For (semi-)continuous data entry. 

Could be same concept as interface sliders; some labelling, step size parameter, ... 
Survey element both within interface (`commentquestion`) and as survey pop-up.

**Comment by nickjillings** [comment]
This has now been implemented in the Dev_main branch (96831b1). There are two schema changes to support this, one is backwards compatible and one is not.

The `<commentquestion>` nodes have been replaced. Instead of listing these as a set of nodes, distinguished by type, they are instead grouped under a new parent node `<commentquestions>` and have specific node types. This is because of the various attributes and child structures that specific types need. It was no longer compatible to maintain it the other way. As a for instance, take this older structure

``` xml
    <commentquestion type="question" id="dmc">
        <statement>Deep and meaningful question</statement>
    </commentquestion>
    <commentquestion type="checkbox" id="only1">
        <statement>Do you like this test?</statement>
        <option name="yes">Yes</option>
    </commentquestion>
```

This is now shown as:
```xml
    <commentquestions>
        <commentquestion id="dmc">
            <statement>Deep and meaningful question</statement>
        </commentquestion>
        <commentcheckbox id="only1">
            <statement>Do you like this test?</statement>
            <option name="yes">Yes</option>
         </commentcheckbox>
    </commentquestions>
```

The conversions are simply 'comment' followed by the type so:
- `<commentquestion type="question">` is `<commentquestion>` (hence the incompatibility).
- `<commentquestion type="checkbox">` is `<commentcheckbox>`
- `<commentquestion type="radio">` is `<commentradio>`

The new slider is called `<commentslider>` and can be structured as:

```xml
<commentslider id="slider" min="0" max="100">
    <statement>Test</statement>
    <minText>Left</minText>
    <maxText>Right</maxText>
</commentslider>
```


For the survey elements, these are backwards compatible, however the console will throw a warning each time a `<surveyelement>` is found. Because the survey elements are nested inside a node already and the name is generic, it is possible to keep these separate. On exporting however it will auto-translate to the new version (ie: there are two decoders, but only one encoder).

The slider element is the same really:

```xml
<surveyslider id="sliders" max="100" min="0">
    <statement>Sliders!!</statement>
    <minText>Lefty</minText>
    <maxText>Righty</maxText>
</surveyslider>
```
