### ISSUE TITLE
Not submitting all test results

### ISSUE THREAD

**Issue by djmoffat** [BrechtDeMan/WebAudioEvaluationTool#144]
Hey,

On branch DaveHack I have had a few participants where they have managed to complete test one, progress to test two and complete it all, but one of the pages in test one has not got any results - test is marked as empty.

Is there some edge case where someone can skip to test 2 without competing test one?

**Comment by nickjillings** [comment]
Is the empty test 1 linked to any completed test 2? Otherwise it may be someone loaded a session, then reloaded it generating a new save structure and creating the orphaned test 1

**Comment by djmoffat** [comment]
Yes,

There is a partially completed test 1 (2 of 3 pages) and then a completed test 2.

I have been dealing with reloads and multiple instances of second pages ect. and cleaned all that up, but cannot get over how someone cannot complete test 1 but still complete test 2.

**Comment by nickjillings** [comment]
In theory, if you load up from test 2 by accident (perhaps a refresh) it will obviously not have a test 1 associated with it.

For an individual page in test 1 not being completed when it should, that is certainly a bug, but not sure which one is the issue here. Test 1 not there or a page in test 1 not there

**Comment by djmoffat** [comment]
There is no way that the person was able to enter the second url with correct key before completing test one - it maybe has more to do with no verification that the page has been submitted before moving onto the URL forwarding.
—
Dave Moffat
07969375889
me@davemoffat.com

**Comment by nickjillings** [comment]
Maybe, there could be a race condition where it moved on before actually submitting the data. Will need to examine the code to see what happened here.

**Comment by nickjillings** [comment]
The code has a checker which means it will only redirect to the new URL once the server has responded with the save OK message. So the file must have been saved before moving on, otherwise it gets presented locally to the user with no way to proceed to test 2. So either the server saved it incorrectly and lost it but still sent a saved OK or it has somehow not been copied and/or deleted somewhere.

**Comment by nickjillings** [comment]
> There is a partially completed test 1 (2 of 3 pages) and then a completed test 2.

Sorry, just re-read this and saw that. So it was definitely not being stored correctly in session! Which is a much bigger issue. Annoyingly it makes it rather impossible to know what happened and therefore what to fix.

**Comment by djmoffat** [comment]
Hey,

I have just had this issue again - twice on a current test I am running, using the latest pull from the main repo - two tests save and provide user with message saying "thank you" but both times only 3 of the 4 pages results have saved.

The large majority of my results are not rendering as complete and are all "updated" - there is clearly a miss-message occuring.

**Comment by nickjillings** [comment]
OK,The latest pulls should now work. All the save communications are in one place now so it's a lot easier to maintain. Also there are distinct update() and finish() functions to ensure the nodes are properly updated.
