### ISSUE TITLE
hanging while submitting

### ISSUE THREAD

**Issue by amilo** [BrechtDeMan/WebAudioEvaluationTool#150]
Hello,
I tried this example with localhost with Firefox and Chrome but it looks like it's not going to the next page and it keeps being stuck on "Submitting. Please Wait".
http://127.0.0.1/waet/test.html?url=tests/examples/horizontal_example.xml

this is the console from Chrome

> Stopped at 23.980408163265306
> core.js:3275 Cannot save as key == null
> core.js:2359 Comment frag-0: 
> core.js:2359 Comment frag-1: 
> 2core.js:3275 Cannot save as key == null
> core.js:1266 Ending test ...
> 2core.js:3275 Cannot save as key == null
> core.js:489 XMLHttpRequest
> core.js:497 Uncaught TypeError: Cannot read property 'getAttribute' of undefined
> core.js:2221 Warning - Interface does not have Resize option
> core.js:2222 TypeError: Cannot read property 'interfaces' of null(…)

**Comment by giuliomoro** [comment]
So this is due to a permission error in apache2.

It is a bug because the dialog should display a meaningful error and offer a download button.

On a separate note, I believe you guys should add this to the wiki to help people get started on localhost on OSX without fiddling around with (evil) XAMPP.

these are the changes I made to my `/etc/httpd.conf` to get this to work using MacOSX's built-in apache2 server, although I believe only the last one is needed, important and relevant: run the local webserver as yourself, so to avoid permissions error.
```
120c120
< #LoadModule expires_module libexec/apache2/mod_expires.so
---
> LoadModule expires_module libexec/apache2/mod_expires.so
142,143d141
< #LoadModule slotmem_plain_module libexec/apache2/mod_slotmem_plain.so
< #LoadModule ssl_module libexec/apache2/mod_ssl.so
169c167
< #LoadModule php5_module libexec/apache2/libphp5.so
---
> LoadModule php5_module libexec/apache2/libphp5.so
181,183c179,182
< User _www
< Group _www
<
---
> User yourUsername
> Group yourGroup
```
Of course you'll also want to make sure that the `saves/` folder is in a writeable location, e.g. in `~/waet/saves` and that Apache can access it e.g. with a symlink:
`sudo ln -s /Users/yourUsername/waet /Library/WebServer/Documents/`

**Comment by nickjillings** [comment]
If being run locally, the Python server should be used which wraps all this up nicely for you. Otherwise you have to look at setting up a full apache server which is cumbersome.

Most likely, I'd say this is being run from a local apache without PHP, or also the permissions issue @giuliomoro said above.

Is there any specific reason you are not using the included python server?

**Comment by giuliomoro** [comment]
My point is, this just happens to be running locally, but it could well happen on a remote server which runs with the same configuration.  The dialog should not hang and a meaningful message should be displayed to the user

**Comment by nickjillings** [comment]
It should be I agree, having read some of the other bug issues, the key returned is a 'null' which should be throwing all kinds of errors. The issue I think is that it is now, most likely by PHP, actually writing the word "null" rather than returning the null string which is just "". So the page key sees the string, it has some value, and moves on.

The PHP file on the server side does have a response state which either returns an OK on the key, reject the key because it is already in use, or respond the error message. Now either the server is just accepting and responding incorrectly or the core is not processing these messages correctly.

**Comment by amilo** [comment]
Hello again, I tried two other examples to familiarise with the interface, and it looks like there might be problems submitting in other forms. In the A/B for example, clicking submitting:
http://localhost/waet/test.html?url=tests/examples/AB_example.xml
It appears a white window and nothing happens after. This is what I get in chrome
![screen shot 2016-09-20 at 18 52 06](https://cloud.githubusercontent.com/assets/8320650/18682494/6000d5bc-7f64-11e6-87fd-4237ec470768.png)

A similar thing happens with mushra
http://localhost/waet/test.html?url=tests/examples/mushra_example.xml
I guess it's still under construction?
![screen shot 2016-09-20 at 19 02 56](https://cloud.githubusercontent.com/assets/8320650/18682654/029b4780-7f65-11e6-96f2-2786aad001b1.png)

**Comment by giuliomoro** [comment]
Can you confirm this happens also with the python server?

**Comment by nickjillings** [comment]
See the other bugs today, this has already been listed and is in process of being fixed.

Sent from my iPhone

On 20 Sep 2016, at 19:07, giuliomoro <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you confirm this happens also with the python server?

-

**Comment by nickjillings** [comment]
Can you please actually confirm if it does actually not save a file? Or simply a recurrence of #148. If it does not actually save anything, can you post / send me your PHP log file?

**Comment by amilo** [comment]
Hello,
I've checked in the `/saves` folder and the horizontal example saves, but not the AB_example. 
Looking at the log from `/private/var/log/apache2/error_log` there was no trace of the missed saving attemps. I've decided to change the `LogLevel` in the `/etc/apache2/httpd.conf `file from `warn` to `debug` (too many lines) and then `info`. I will email to you the different logs.

**Comment by nickjillings** [comment]
Thanks for the logs. Annoyingly OSX seems to be very unhelpful because it simply states: 

> Symbolic link not allowed or link target not accessible

Without specifying the filename, which may indicate that the link is broken internally. More likely however is that, the service should not be used with symbolic links (perhaps as a security measure to prevent hosting in a protected space like your home directory).

**Comment by nickjillings** [comment]
This should be fixed now @amilo, if you would like to update and retry. The issue came from a typo in the key checking file. It now uses a different system which should be more robust.

**Comment by nickjillings** [comment]
Assumed resolved as all other scenarios point to resolved, along with testing.
