### ISSUE TITLE
console in firefox spits out lots of garbage

### ISSUE THREAD

**Issue by giuliomoro** [BrechtDeMan/WebAudioEvaluationTool#152]
Give it at try.
Firefox 48.0.1 on Mac OSX 10.10

**Comment by nickjillings** [comment]
What kind of 'garbage'. I'm not seeing anything unusual

**Comment by giuliomoro** [comment]
@amilo  can you post a screenshot of your Firefox console ?

**Comment by amilo** [comment]
![screen shot 2016-09-20 at 18 14 32](https://cloud.githubusercontent.com/assets/8320650/18681147/a6a40b5c-7f5e-11e6-833c-e0621575e6a3.png)

**Comment by nickjillings** [comment]
I think this is related to #150 as it is simply reporting that a document it is downloading is holding junk. This would make sense since the key system continually polls until a key can be found. Can you confirm you don't get any console errors @amilo on this [link.](http://dmtlab.bcu.ac.uk/nickjillings/waet/test.html?url=tests/examples/horizontal_example.xml)

**Comment by amilo** [comment]
@nickjillings @giuliomoro I confirm
![screen shot 2016-09-20 at 18 28 43](https://cloud.githubusercontent.com/assets/8320650/18681461/230a19a6-7f60-11e6-89c6-871e63696dbd.png)

**Comment by nickjillings** [comment]
OK, then I think there are more server issues relating to #150 causing its in-built error throwing to collapse. I'll close this as the other issue is the real issue.

**Comment by nickjillings** [comment]
FYI @amilo and @giuliomoro. The issues surrounding this has been fixed. If you update to the latest master branch commit then you shouldn't have any more problems
