### ISSUE TITLE
More rigorous master branch review

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#153]
In light of a few bugs that were not there before, I've been wondering if master branch commits should be subject to a more rigorous process to reduce the risk of breaking existing functionality. I think we are coming quite close to getting the basic functionality just right, at which point it should really not be touched unless we are more or less certain the improved code or extra features don't introduce bugs. 

I don't think code reviews are necessary or even possible, but perhaps hot fixes and merges with the master branch should only be made after testing a few example projects. 
I would quite gladly volunteer to run a few of these on a few browsers and log any issues, e.g. every time a milestone is almost reached on the dev_main branch. 

This might mean rethinking and improving a couple of example projects so that a wide range of functionality is effectively tested. These should also make it easy for the developer to quickly test their latest changes. 

Perhaps a viable process is to establish who has which platforms available, then open a 'sprint' issue here every time a set of new changes are to be tested, so we can log what problems we're seeing. 
I could also set up a server where I can pull the latest version of WAET every now and then, for demos and testing. Scripting a 'git hook' for this would be ideal though I don't have the time myself to look into how to do this. 

Unit tests (#113) would also still be great, but I don't think they could easily prevent this type of problems. 

Thoughts? @nickjillings @djmoffat @giuliomoro

**Comment by nickjillings** [comment]
I've looking into travis CI before, when you first raised it in #113. It doesn't seem to work well with purely client side environments. However it could certainly be used for the PHP and python scripts.

There is a javascript environment called PhantomJS which is effectively a virtual browser which will allow us to, say, virtually run a test and monitor if the output matches against a sample XML. Otherwise we can use this as well to simply stress test each function and monitor the objects coming back.

My real question is, if this will save time rather than perhaps writing a user level checklist which we must ensure works for each deployment.

In terms of git branching, I agree perhaps the master branch is too liberally used which causes some problems. I think we should have another branch, perhaps 'testing' or 'beta' or 'deployment' as a staging where we can all evaluate it before it gets released onto the master, however the issue still arises with the recent bugs. It will not clean it up if a bug is found on master and needs a hot_fix, however it should make staging and hopefully detecting bugs a little bit easier.

Also deployment should be hooked into the 'test' or 'beta' branch as often as possible to reduce the chances of having to do three-way merges.

**Comment by BrechtDeMan** [comment]
Great points. 

I absolutely agree with this: 

> writing a user level checklist which we must ensure works for each deployment

and that's sort of what I was thinking of. 

Travis CI and PhantomJS seem worth looking into, though to be considered thoroughly what the costs and benefits are. 

A beta branch seems very sensible, though dev_main could be used for a lot of this. But yes perhaps only a stable, '1.x.y' release should be on master with more minor upgrades on a beta one, if the dev_main is getting more experimental. 
Of course urgent hot fixes should be done on the master branch, but then also some testing is in order.

**Comment by nickjillings** [comment]
> Travis CI and PhantomJS seem worth looking into, though to be considered thoroughly what the costs and benefits are. 

That's my worry with it, that we create an amazing test suite but we have to rewrite parts of it all the time to keep up. I think after the rewrite certain tests will be much easier to do, especially on the interface as I'm planning on getting those to be an object rather than global functions (enabling multiple interfaces in one session to be a thing).

For the PHP and python server stuff that should be OK but if we change the behavior we then have to change the tests. So I'm not sure how suited to this project actually these are.

> A beta branch seems very sensible, though dev_main could be used for a lot of this.

Yes, but I think there just needs to be a bit more separation as it is now so big that making parallel changes becomes difficult and then we have to use the master. Since we are now doing deployments rather than pushing, the master should be kept free.

**Comment by BrechtDeMan** [comment]
Yes, agreed. Let's focus on 

1. keeping the master branch free from anything but thoroughly tested new versions and important (and ideally also relatively well-tested) hotfixes - i.e. make a new, less stable 'next version' branch.
2. testing using example projects after each significant update, and if necessary improving the example projects (so that we don't need 20, but we've got a handful that cover most or all functionality). Could do a quick diff of XMLs I guess, and produce 'canonical' XML outputs to compare against.

**Comment by giuliomoro** [comment]
one option is that you cherry-pick critical fixes into master.

**Comment by nickjillings** [comment]
@giuliomoro this works if the two branches you are pulling from are common enough or changes are occuring in the same base, but yes these are useful.

For the most part, I think master is only for releases and hot fixes, for this reason hot fix should remain but only as a time machine really for pushing critical fixes. Then a vnext branch for new features and finally the Dev_main for actually building tests.

I'll also set up and keep all three branches maintained on the dmtlab server, under dmtlab.co.uk/nickjillings/waet(-vnext/-dev).

If we are all happy with this moving forward, I'll deploy it once the latest round of Dev_main stuff has been tested.

**Comment by nickjillings** [comment]
OK, I've added the vnext branch, currently tracking at the same point as Dev_main. It should be at a somewhat sane sense right now.
