### ISSUE TITLE
Calibration: channel check

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#171]
Establish where users hear left and right.

(Radio) buttons to denote whether a beep/noise (generated using Web Audio API) comes from left, right or centre channel. 

In reality, I believe the stimuli being used should be left and right only. (Phantom centre not necessary, but the 'centre' option allows identifying a 'mono' system) One dialog box per option. 

More detailed diagnostics are also possible, e.g. a slider with stimuli of various degrees of panning, though this could be mimicked with an APE or horizontal style interface easily. 

(Stretch goal: surround, much less widely applicable)

**Comment by nickjillings** [comment]
Milestone v1.2.3 will now be a breaking release, but the fix is quite simple. The attribute `calibration` in the `<setup>` tag is depricated. A new calibration element instead should be used. It has three different attributes to enable the test types:

- `checkFrequencies`: User to adjust different tones until all are equally heard
- `checkLevels`: User to adjust a noisy signal until a comfortable level
- `checkChannels`: User to indicate where a sound is coming from

Example:
```xml
<setup ...>
  <calibration checkFrequencies="true" />
  ...
</setup>
```

**Comment by nickjillings** [comment]
When the calibration element has `checkChannels="true"` then the channel checker is shown pre-test.

![capture](https://user-images.githubusercontent.com/5649114/35057746-cfe3021c-fbad-11e7-8ad8-da741fe80241.PNG)

The "to be beautified" interface above is shown to the user. When play is clicked, a tone is sent either hard left or right. The user must then selected "Left", "Middle" or "Right" to describe the sound.

I am thinking maybe a scale, but that opens a whole other can of worms!

In the results:
```xml
<calibration>
   <channels presented="1" presentedText="Right" selected="1" selectedText="Right" />
</calibration>
```
