### ISSUE TITLE
Limit number of plays

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#209]
Enforce a maximum number of plays for an audioelement (or page or test-wide) when a sample cannot be played back more than X times. 

E.g. <audioelement ... maxNumberPlays=1 />

**Comment by djmoffat** [comment]
+1

**Comment by nickjillings** [comment]
Can also make this a per-page and global feature:
`<setup ... maxNumberPlays="1" />`
`<page... maxNumberPlays="1" />`
`<audioelement... maxNumberPlays="1" />`

Perhaps also a `minNumberPlays` as well?

**Comment by BrechtDeMan** [comment]
I thought of that, it's possible of course, though note the overlap with `<check name="fragmentPlayed"/>`. This could become obsolete or just coexist. 

Should it also have some checking, e.g. `minNumberPlays`>0, `maxNumberPlays`>1, `maxNumberPlays` >= `minNumberPlays`?

**Comment by nickjillings** [comment]
The fragment played check will simply co-exist since fragmentPlayed effectively does 'are all tracks play counts > 0'. So if minNumberPlays="0" and this is on, that's the only conflicting statement, but that's also the general statement.

minNumberPlays default should be 0. The default is the undefined state. maxNumberPlays default should be the undefined state so it is never checked. Otherwise yes the check will be if both defined the range must be valid.

**Comment by BrechtDeMan** [comment]
Agreed.

**Comment by nickjillings** [comment]
I've implemented this now and pushed into all branches.

By default the minimum number of plays is 0 (and as of yet no check) but the maximum number of plays can be enforced to any integer value.

The original requestor for this can therefore use the `maxNumberPlays="1"` now.

**Comment by nickjillings** [comment]
Both `minNumberPlays` and `maxNumberPlays` have been added with complete checks.

These have also been added to the new test_create.html in b8ae4ab
