### ISSUE TITLE
ABX execution and online analysis issue

### ISSUE THREAD

**Issue by fuyang2032** [BrechtDeMan/WebAudioEvaluationTool#214]
I am told to put this as a new issue here (followed by issue #204) 
------
There may be something wrong during the execution of ABX_example in the Dev_main (X does not appear, neither A nor B can be chosen by click)
![image](https://user-images.githubusercontent.com/26958604/27482583-f36214f4-5819-11e7-89b2-2bcd794abd73.png)

The ABX_example in vnext is fine as I tried, but the outcome file in the saves branch cannot be recognized by the online analysis tool
![image](https://user-images.githubusercontent.com/26958604/27482724-77e3c8b2-581a-11e7-9e2c-540d8c2272dd.png)
![image](https://user-images.githubusercontent.com/26958604/27483431-45611c5c-581d-11e7-9e61-3c87a4637ad5.png)

**Comment by nickjillings** [comment]
Fixed in cfff726

The online analysis should be in a separate issue as well, this keeps it easier to track and find related issues and group them together.

This won't be fixed soon due to the number of more pressing issues. However the tool does have the python scripts to parse the results files which are more powerful.
