### ISSUE TITLE
Request or enforce bit depth from audio driver/hardware

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#240]
For critical tests, the bit depth could be requested and compared to an optional value in the specification (in addition to the already implemented sample rate check). 

This is necessary for tests where e.g. audibility of bit depth differences is being investigated.

**Comment by nickjillings** [comment]
This part is not feasible to enforce. Web Audio API automatically converts all items to 32-bit FP precision, since all OSes use this as the intermediary format, only converting back at the sound card. Bit enforcement can only be specified by the files being used. The API also does not report what the soundcard bit-depth is for the same reason.

**Comment by BrechtDeMan** [comment]
Interesting, thanks! 

This was inspired by "Depending on audio driver and configuration it is possible to specify desired buffer size, sample rate and channel count for the hardware. Also, it is possible to request information of bit-depth (sample format) at the hardware level as to obtain “bit perfect” playback." from _Benjamin Pedersen "Hi-precision audio in listening tests - also in the browser?" 3rd Web Audio Conference, August 2017._ but I guess they were talking about ASIO etc. and not Web Audio API / browser applications.
