### ISSUE TITLE
Keyboard shortcuts for playback

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#243]
Came up for ABX by someone designing a test (so relatively urgent). Could work for basically any interface. 

E.g. 

- '1' is the first element (could be '1', or 'A'), '2', '3', ... 
- 'X' is the 'X' of 'AB(CD...)X'
- spacebar to stop audio altogether

Original comment: "I really missed the possibility of having a physical control to switch between streams (could be the computer keys) as I found myself to be very prone to listening to differences with my eyes shut (which makes it difficult to hit buttons with the mouse)."

**Comment by nickjillings** [comment]
I'm not sure the number clicking would be useful, but maybe the spacebar and then arrow keys to scroll between the different samples.

The number keys can be bound though, for sure, but it only makes sense if the element itself is a number. The letter ones may not make any sense then because you'd be focused on the keyboard.

Anyway, I guess they can all be added to master if it is a priority.

**Comment by nickjillings** [comment]
This is now implemented into master on 6b0ce71.

Behaviour is as follows:

- Space bar: Stop any currently playing audio
- Numbers / Letters: Play corresponding audio sample

If there are no numbers/letters on the markers, then no keys are bounded to avoid giving away any test order that is designed to be hidden.
