### ISSUE TITLE
Firefox stimuli piling up

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#249]
Firefox (v56, on Mac OS X 10.10 as well as 10.11) consistently keeps playing the previous stimuli when switching to another one, until the 'Stop' button is hit. So you get the sum of all clicked stimuli so far. This is for the case where they are both looped and synchronised.  

You can see this in the `tests/examples/APE_example.xml` when setting `synchronous="true"`.

I had the impression this happened to me at least once in Safari but haven't been able to reproduce that.

**Comment by nickjillings** [comment]
It seems that the behaviour has changed again since I implemented the new playback schedulers a few months ago.

Have triaged and will fix it now. It effectively comes down to a bug where the Firefox WAAPI implementation does not update the DOM of the current gain when using curves. So if I tell it to ramp from 0 to 1 over 3 seconds, it will do that, but the gain value will still hold the number 0 despite it actually being at 1.

This is also in v57.0a2 (current developer edition) so needs to be fixed.

**Comment by nickjillings** [comment]
Fixed in 88e0701
