### ISSUE TITLE
Explicitly set label for audioelements

### ISSUE THREAD

**Issue by giuliomoro** [BrechtDeMan/WebAudioEvaluationTool#37]
e.g.: in AB tests

**Comment by nickjillings** [comment]
I'm assuming this is for a non-randomised pool as, post randomisation, each element will still have its given label.

Instead of mucking with label perhaps the element should have a label (or some other attribute name, like givenLabel or forcedLabel) which is always used for that element irrelevant of the page label type.

Having the label="given" as in your commit, then you would have to force the label of every element rather than just having an override for a few?

Otherwise, if you wanted to have [x,y,z] instead of [a,b,c], perhaps a label-offset attribute would be a little neater?

**Comment by nickjillings** [comment]
Completed in Dev_main. Now each `<page>` node has two extra attributes, `label` and `labelStart`. Label can be number, letter, capital, none or default. Label start can be a sensible starting character. For instance:

`<page label="number" labelStart="4">` would create 4, 5, 6 etc
`<page label="capital" labelStart="X">` would create X, Y, Z, A etc
`<page label="capital" labelStart="4">` would default to an invalid label start, so would create A, B, C etc.
