### ISSUE TITLE
specification.projectReturn is ignored

### ISSUE THREAD

**Issue by giuliomoro** [BrechtDeMan/WebAudioEvaluationTool#39]
It is used at line 2866 but ignored at 411 of core.js
````js
411                 xmlhttp.open("POST","php/save.php?key="+storage.SessionKey.key,true);
2866             xmlhttp.open("POST","php/"+specification.projectReturn+"?key="+this.key)
````

**Comment by nickjillings** [comment]
The `<setup projectReturn="">` attribute is now for defining the server to return the test state too. For instance a test could be hosted at example1.com but you want to store the results at example2.com, you can use projectReturn to direct it to the WAET instance on a different server URL.

The projectReturn attribute is ignored unless it starts with "http" (https also supported since it starts with http)

**Comment by nickjillings** [comment]
Note, to support this, the third-party server must have Access-Control-Allow-Origin on its communications to either all domains or the domain where the third party is hosted. I'm not sure if we should enable this by default or not though

**Comment by giuliomoro** [comment]
so are both the lines I mentioned above wrong?

**Comment by nickjillings** [comment]
They've both been edited now to integrate with the changes. They are both the same now. I might collapse createSessionSave() into the storage.SessionKey object to have only one place for server communications anyway.
