### ISSUE TITLE
Force scrollbar on popup to be displayed ...

### ISSUE THREAD

**Issue by giuliomoro** [BrechtDeMan/WebAudioEvaluationTool#62]
When the content of the popup is longer than the available space, a scroll bar should be displayed. MacOS has some global system settings to disable scrollbars until you start scrolling (CLEVER, INNIT?).
This should fix it http://stackoverflow.com/a/10100209

**Comment by nickjillings** [comment]
This causes the horizontal scroll-bar to always be shown which is a problem. Far better to tell the system to always make space for the vertical scroll-bar. If content is too long for the box that is a rendering problem and should be fixed rather than through messy scroll-bars.

Plus using ::webkit only creates issues in Firefox and Edge
