### ISSUE TITLE
Intermediate saving all files as save-null.xml when using pool.php

### ISSUE THREAD

**Issue by adibmehrabi** [BrechtDeMan/WebAudioEvaluationTool#67]
It seems to save with a unique id properly on the final save, but intermediate saves are being created using save-null.xml, which keep getting overridden with the latest save.

**Comment by nickjillings** [comment]
Is this with the python server or PHP servers? This bug has appeared before but believed it had been solved.

**Comment by nickjillings** [comment]
Sorry, re-read question as pool.php

**Comment by giuliomoro** [comment]
Php apache2

**Comment by nickjillings** [comment]
I believe this is caused by a race condition. The client generates a key and asks the server to verify the key is unique (no other saves exist). If it is unique, the client uses that key, otherwise it generates a new key and round and round it goes.

However during this time the storage for the "key" variable is initialised to the special javascript object 'null' which converts literally as such to a string.

On loading of the script, an initial save is done. There is a possibility that the initial save is performed before the server has responded with the key, causing the save-null.xml file to appear.
