### ISSUE TITLE
test_create: disable irrelevant options

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#97]
While in the first few pages of test_create (see #84) the option check boxes are checked, unchecked or disabled properly, they are not in the final, full test_create interface. 

E.g. for AB tests, the check boxes for 'Element Initial Position' and 'Element Moved Flag' should be disabled. 

Logged as enhancement as they do not break any functionality, it's mostly confusing and cluttered.

**Comment by nickjillings** [comment]
So the behaviour I'm going for is this;

If the feature is not supported by the interface: it is removed as an option entirely
If the feature is not supported because it will break the desired test protocal: it will be disabled

Right now this will be a 'hard' selection, hopefully in the future it could say 'Well you can disable that, but it won't be MUSHRA anymore' messages.

**Comment by BrechtDeMan** [comment]
> 'Well you can disable that, but it won't be MUSHRA anymore' messages

Preferably including a 'Fraunie' - a Fraunhofer scientist frowning.

**Comment by nickjillings** [comment]
These should now be configured. However we ( @BrechtDeMan @djmoffat ) need to ensure that the specification of the listening tests are correct.

The format is stored in JSON in `/test_create/interfaces/specifications.json`. Equally any new test layouts can be added here.
